import type { FallbackScenario } from './types'

export const hematologyFallbackScenarios: FallbackScenario[] = [
  {
    key: 'heme-itp-olivia-easy-bruising',
    titleMatchers: ['bruise from everything', 'bruises everywhere'],
    complaintMatchers: ['finding bruises'],
    defaultAnswer:
      "Bruises from nothing dramatic—nosebleeds mornings—gums bleed brushing—no fever—three weeks creeping terror it’s leukemia from internet doom.",
    qa: [
      { id: 'chief', answer: "Random bruises everywhere—sounds fake until mirror proves.", patterns: ['chief', 'bring'], keywords: ['chief'] },
      { id: 'bruise', answer: "Thighs calves galaxy purple—backpack strap leaves stamp.", patterns: ['bruise'], keywords: ['bruise'] },
      { id: 'nose', answer: "Epic nosebleeds twice—bathroom crime scene.", patterns: ['nose', 'epistaxis'], keywords: ['nose'] },
      { id: 'gum', answer: "Toothbrush pink spit every night.", patterns: ['gum', 'mouth'], keywords: ['gum'] },
      { id: 'period', answer: "Heavier period maybe—pads changed faster.", patterns: ['period', 'menstrual'], keywords: ['period'] },
      { id: 'family', answer: "No family bleeding drama parents claim.", patterns: ['family'], keywords: ['family'] },
      { id: 'med', answer: "Ibuprofen cramps gummy vitamins only.", patterns: ['med'], keywords: ['med'] },
      { id: 'fever', answer: "No fever—energy weirdly intact.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'trauma', answer: "No injury warranting mural art bruises.", patterns: ['trauma'], keywords: ['trauma'] },
      { id: 'transfusion', answer: "Never transfused.", patterns: ['transfus'], keywords: ['transfus'] },
      { id: 'fatigue', answer: "Anxiety tired more than body crash.", patterns: ['fatigue'], keywords: ['fatigue'] },
      { id: 'timing', answer: "Three week slide.", patterns: ['how long'], keywords: ['long'] },
      { id: 'help', answer: "Ice theater worthless—pressure nose helped bleeds.", patterns: ['help'], keywords: ['help'] },
      { id: 'appetite', answer: "Eating fine—stress chocolate.", patterns: ['appetite'], keywords: ['appetite'] },
      { id: 'infection', answer: "No infection saga.", patterns: ['infection'], keywords: ['infection'] },
      { id: 'vague', answer: "Teen brain—rephrase?", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
  {
    key: 'heme-iron-jessica-fatigue-sob',
    titleMatchers: ['tired and short of breath', 'short of breath'],
    complaintMatchers: ['no energy'],
    defaultAnswer:
      "Months fatigue stairs winded—periods flood—chews ice compulsively—dizzy sometimes—teacher pride dying quietly.",
    qa: [
      { id: 'chief', answer: "Zero energy semester from hell.", patterns: ['chief'], keywords: ['chief'] },
      { id: 'fatigue', answer: "Grading fog marathon.", patterns: ['fatigue', 'tired'], keywords: ['fatigue'] },
      { id: 'sob', answer: "Hallways breathless joke.", patterns: ['breath', 'short'], keywords: ['breath'] },
      { id: 'period', answer: "Menorrhagia monster clots.", patterns: ['period', 'bleed'], keywords: ['period'] },
      { id: 'ice', answer: "Freezer pellet chewing shame.", patterns: ['ice', 'pica'], keywords: ['ice'] },
      { id: 'dizz', answer: "Standing dizzy spells.", patterns: ['dizz'], keywords: ['dizz'] },
      { id: 'family', answer: "Mom anemia vague heritage.", patterns: ['family'], keywords: ['family'] },
      { id: 'gi', answer: "Stool normal—no melena.", patterns: ['stool', 'gi'], keywords: ['stool'] },
      { id: 'diet', answer: "Vegetarian-ish weekdays.", patterns: ['diet'], keywords: ['diet'] },
      { id: 'transfusion', answer: "Never transfused.", patterns: ['transfus'], keywords: ['transfus'] },
      { id: 'med', answer: "Spare iron bottles GI quit.", patterns: ['med'], keywords: ['med'] },
      { id: 'timing', answer: "Semester worsening.", patterns: ['how long'], keywords: ['long'] },
      { id: 'help', answer: "Sitting beats walking.", patterns: ['help'], keywords: ['help'] },
      { id: 'fever', answer: "Afebrile.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'bruise', answer: "Bruising not headline.", patterns: ['bruise'], keywords: ['bruise'] },
      { id: 'vague', answer: "Clarify please.", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
  {
    key: 'heme-hodgkin-andrew-cervical-nodes',
    titleMatchers: ['neck keeps swelling', 'lumps in my neck'],
    complaintMatchers: ['lumps in my neck'],
    defaultAnswer:
      "Rubbery neck nodes months—night sweats—weight down—fevers evenings—grad school denial cracking.",
    qa: [
      { id: 'chief', answer: "Neck lumps roommate clocked.", patterns: ['chief'], keywords: ['chief'] },
      { id: 'node', answer: "Painless growing wrong.", patterns: ['lump', 'node'], keywords: ['lump'] },
      { id: 'sweat', answer: "Sheets soaked laundry joke dead.", patterns: ['sweat', 'night'], keywords: ['sweat'] },
      { id: 'weight', answer: "Belt loose appetite ghost.", patterns: ['weight'], keywords: ['weight'] },
      { id: 'fever', answer: "Low grade thermostat drama.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'fatigue', answer: "Seminar brain fog.", patterns: ['fatigue'], keywords: ['fatigue'] },
      { id: 'pain', answer: "Nodes painless guilt.", patterns: ['pain'], keywords: ['pain'] },
      { id: 'family', answer: "Uncle lymph whispers.", patterns: ['family'], keywords: ['family'] },
      { id: 'hiv', answer: "College HIV test negative year ago.", patterns: ['hiv'], keywords: ['hiv'] },
      { id: 'transfusion', answer: "Never transfused.", patterns: ['transfus'], keywords: ['transfus'] },
      { id: 'med', answer: "Ibuprofen finals only.", patterns: ['med'], keywords: ['med'] },
      { id: 'bleed', answer: "No big bleeding.", patterns: ['bleed'], keywords: ['bleed'] },
      { id: 'cough', answer: "Mild cough dorm maybe.", patterns: ['cough'], keywords: ['cough'] },
      { id: 'timing', answer: "Months B symptom crescendo.", patterns: ['how long'], keywords: ['long'] },
      { id: 'help', answer: "Naps fake function.", patterns: ['help'], keywords: ['help'] },
      { id: 'vague', answer: "Rephrase scared grad student.", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
  {
    key: 'heme-sickle-marcus-voc',
    titleMatchers: ['legs hurt', 'feel weak'],
    complaintMatchers: ['whole body hurts'],
    defaultAnswer:
      "Known SS—dehydrated football tryout—legs back pain crescendo—familiar crisis worse wave—hydroxyurea adherence garbage confession.",
    qa: [
      { id: 'chief', answer: "Body pain monster return.", patterns: ['chief'], keywords: ['chief'] },
      { id: 'pain', answer: "Legs back vise ensemble.", patterns: ['pain'], keywords: ['pain'] },
      { id: 'sickle', answer: "SS lifelong—crisis pattern known.", patterns: ['sickle'], keywords: ['sickle'] },
      { id: 'trigger', answer: "Hot field no water stupidity.", patterns: ['dehydrat', 'sport'], keywords: ['dehydrat'] },
      { id: 'fever', answer: "Maybe low grade—uncertain pain blur.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'transfusion', answer: "Once childhood infusion memory.", patterns: ['transfus'], keywords: ['transfus'] },
      { id: 'family', answer: "Sister trait carriers parents.", patterns: ['family'], keywords: ['family'] },
      { id: 'weak', answer: "Drained not paralyzed.", patterns: ['weak'], keywords: ['weak'] },
      { id: 'trauma', answer: "No tackle snap.", patterns: ['trauma'], keywords: ['trauma'] },
      { id: 'breath', answer: "Air okayish scare acute chest google.", patterns: ['breath'], keywords: ['breath'] },
      { id: 'med', answer: "Hydroxyurea missed doses—ibuprofen weak.", patterns: ['med'], keywords: ['med'] },
      { id: 'timing', answer: "Post-practice escalation hours.", patterns: ['when'], keywords: ['when'] },
      { id: 'help', answer: "Curl position slight mercy.", patterns: ['help'], keywords: ['help'] },
      { id: 'walk', answer: "Limps deteriorating.", patterns: ['walk'], keywords: ['walk'] },
      { id: 'numb', answer: "Numb not headline.", patterns: ['numb'], keywords: ['numb'] },
      { id: 'vague', answer: "Teen pride rephrase?", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
  {
    key: 'heme-acute-leukemia-noah-infections',
    titleMatchers: ['fevers and infections', 'getting sick'],
    complaintMatchers: ['keeps getting sick'],
    defaultAnswer:
      "Mom voice: repeat infections fevers—pale bruise dots—bone ache nights—Noah quiet scared—no transfusions yet.",
    qa: [
      { id: 'chief', answer: "Mom: sick loop endless.", patterns: ['chief'], keywords: ['chief'] },
      { id: 'infection', answer: "Ear infections pneumonias revolving door.", patterns: ['infection', 'ear'], keywords: ['infection'] },
      { id: 'fever', answer: "Nights 101 Tylenol dance.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'bruise', answer: "Purple speckle legs soap switch failed.", patterns: ['bruise'], keywords: ['bruise'] },
      { id: 'bone', answer: "Shin ache wakes crying.", patterns: ['bone', 'pain'], keywords: ['bone'] },
      { id: 'tired', answer: "Cartoon stamina gone.", patterns: ['tired'], keywords: ['tired'] },
      { id: 'belly', answer: "Tummy pressed hurts full.", patterns: ['belly', 'liver'], keywords: ['belly'] },
      { id: 'transfusion', answer: "Never yet needle fear.", patterns: ['transfus'], keywords: ['transfus'] },
      { id: 'vaccine', answer: "Mom thinks shots okay—flu mist missed.", patterns: ['vaccine'], keywords: ['vaccine'] },
      { id: 'appetite', answer: "Mac nibbles only.", patterns: ['appetite'], keywords: ['appetite'] },
      { id: 'sibling', answer: "Brother asthma not this.", patterns: ['brother'], keywords: ['brother'] },
      { id: 'med', answer: "Kid Motrin sporadic.", patterns: ['med'], keywords: ['med'] },
      { id: 'timing', answer: "Months decline.", patterns: ['how long'], keywords: ['long'] },
      { id: 'help', answer: "Mom cuddle nights help fear.", patterns: ['help'], keywords: ['help'] },
      { id: 'scared', answer: "Bathroom dying whisper overheard.", patterns: ['scared', 'worried'], keywords: ['scared'] },
      { id: 'bleed', answer: "No gush bleeds—dots only.", patterns: ['bleed'], keywords: ['bleed'] },
      { id: 'vague', answer: "Nine-year-old confused simplify.", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
]
