import type { FallbackScenario } from './types'

export const obgynFallbackScenarios: FallbackScenario[] = [
  {
    key: 'obgyn-ectopic-jessica-missed-period',
    titleMatchers: ['lower belly hurts', "i'm late", 'missed period'],
    complaintMatchers: ['stomach hurts', 'period never came'],
    defaultAnswer:
      "Left-sided lower belly pain since this morning—sharp when I move—with pink-brown spotting. Period skipped six weeks I blamed stress—now lightheaded standing. Sexually active, condoms inconsistent sometimes.",
    qa: [
      { id: 'chief', answer: "Stomach hurts on the left and my period never showed—spotting started yesterday.", patterns: ['chief', 'bring', 'today'], keywords: ['chief', 'bring', 'today'] },
      { id: 'lmp', answer: "Last normal flow about six weeks ago—apps on my phone disagree with my denial.", patterns: ['lmp', 'last period', 'menstrual'], keywords: ['period', 'lmp', 'menstrual'] },
      { id: 'pain', answer: "Deep stab low left—constant ache under it—worse bumping car rides.", patterns: ['pain', 'hurt', 'cramp'], keywords: ['pain', 'hurt', 'cramp'] },
      { id: 'bleed', answer: "Spotting not a real period—liner stains embarrassed me in seminar.", patterns: ['bleed', 'spot', 'discharge'], keywords: ['bleed', 'spot'] },
      { id: 'pregnancy', answer: "Home test procrastinated—wanted calmer week—now ER fears.", patterns: ['pregnant', 'pregnancy', 'test'], keywords: ['pregnant', 'pregnancy'] },
      { id: 'sex', answer: "Boyfriend—sometimes condoms—sometimes dumb nights—no IUD.", patterns: ['sex', 'partner', 'contracept'], keywords: ['sex', 'partner', 'contracept'] },
      { id: 'dizz', answer: "Gray tunnel standing from chair—grabbed wall—not full faint.", patterns: ['dizz', 'lightheaded', 'faint'], keywords: ['dizz', 'faint'] },
      { id: 'fever', answer: "No shaking chills story—maybe warm from stress.", patterns: ['fever', 'temperature', 'chill'], keywords: ['fever', 'temperature'] },
      { id: 'obhx', answer: "G1P0—never carried before—first maybe-hope situation.", patterns: ['gravida', 'parity', 'ob history'], keywords: ['gravida', 'parity', 'pregnancy'] },
      { id: 'uti', answer: "Peeing normal—no burning trail.", patterns: ['uti', 'urine', 'burn'], keywords: ['uti', 'urine'] },
      { id: 'nausea', answer: "Nausea from pain maybe—no vomiting fountain.", patterns: ['nausea', 'vomit'], keywords: ['nausea', 'vomit'] },
      { id: 'timing', answer: "Bad phase escalated hours this morning—fear sped triage.", patterns: ['when', 'how long', 'onset'], keywords: ['when', 'onset', 'long'] },
      { id: 'help', answer: "Curled slightly softer—straightening jolts—no fix.", patterns: ['better', 'worse', 'help'], keywords: ['better', 'worse', 'help'] },
      { id: 'med', answer: "Random vitamins—no daily scripts.", patterns: ['med', 'medication', 'drug'], keywords: ['med', 'medication'] },
      { id: 'family', answer: "Family whisper diagnoses—cousin ER vague—useless genealogy.", patterns: ['family', 'history'], keywords: ['family', 'history'] },
      { id: 'rupture', answer: "Internet horror stories—trying breathe—pain scary enough.", patterns: ['rupture', 'worst', 'tube'], keywords: ['rupture', 'worst'] },
      { id: 'vague', answer: "Grad student brain fog—ask clearer?", patterns: ['understand', 'repeat'], keywords: ['understand', 'repeat'] },
    ],
  },
  {
    key: 'obgyn-pcos-emily-irregular-cycles',
    titleMatchers: ['unpredictable', 'periods'],
    complaintMatchers: ['all over the place', 'irregular'],
    defaultAnswer:
      "Periods vanish months between—chin hair pluck ritual—jaw acne back—weight climbed in college. Condoms sometimes at parties—not planning pregnancy.",
    qa: [
      { id: 'chief', answer: "Periods chaos—schedule joke.", patterns: ['chief', 'bring'], keywords: ['chief', 'bring'] },
      { id: 'period', answer: "Maybe real bleed three months ago—dates messy.", patterns: ['period', 'lmp', 'cycle'], keywords: ['period', 'lmp', 'cycle'] },
      { id: 'hair', answer: "Terminal chin hairs—tweeze mirror lecture.", patterns: ['hair', 'hirsut', 'facial'], keywords: ['hair', 'hirsut'] },
      { id: 'acne', answer: "Jawline inflammatory zits—high school flashback worse.", patterns: ['acne', 'skin'], keywords: ['acne', 'skin'] },
      { id: 'weight', answer: "Dining hall twenty-five pounds—scales avoidance sport.", patterns: ['weight', 'gain', 'bmi'], keywords: ['weight', 'gain'] },
      { id: 'pelvicpain', answer: "Pelvic pain mild—not why I'm here.", patterns: ['pelvic', 'pain'], keywords: ['pelvic', 'pain'] },
      { id: 'pregnancy', answer: "Not trying—could test anxious.", patterns: ['pregnant', 'pregnancy'], keywords: ['pregnant', 'pregnancy'] },
      { id: 'sex', answer: "Partners exist—protection imperfect—shame admitted.", patterns: ['sex', 'partner', 'contracept'], keywords: ['sex', 'contracept'] },
      { id: 'fatigue', answer: "Tired—sleep debt versus hormones who knows.", patterns: ['fatigue', 'tired'], keywords: ['fatigue', 'tired'] },
      { id: 'thyroid', answer: "Mom thyroid whisper—no useful records.", patterns: ['thyroid', 'tsh'], keywords: ['thyroid', 'tsh'] },
      { id: 'galactorrhea', answer: "No nipple discharge horror.", patterns: ['breast', 'nipple', 'milk'], keywords: ['breast', 'nipple'] },
      { id: 'fever', answer: "No fever chronic story.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'discharge', answer: "Discharge baseline normal-ish.", patterns: ['discharge'], keywords: ['discharge'] },
      { id: 'timing', answer: "Years irregular—worse since campus.", patterns: ['how long', 'years'], keywords: ['long', 'years'] },
      { id: 'med', answer: "Spotify-tier vitamin discipline.", patterns: ['med', 'medication'], keywords: ['med', 'medication'] },
      { id: 'help', answer: "Influencer dairy cut—skin stubborn.", patterns: ['help', 'worse'], keywords: ['help', 'worse'] },
      { id: 'vague', answer: "Need simpler question.", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
  {
    key: 'obgyn-miscarriage-ashley-bleeding',
    titleMatchers: ['bleeding and cramping', 'bleeding'],
    complaintMatchers: ['pregnant and bleeding'],
    defaultAnswer:
      "Roughly eight-week pregnancy joy fading—pads soaked bright red—crampy waves—toddler home with spouse. No fever—terror cousin ectopic story loops.",
    qa: [
      { id: 'chief', answer: "Pregnant bleeding—sorry crying.", patterns: ['chief', 'bring'], keywords: ['chief'] },
      { id: 'bleed', answer: "Heavy today—two pads—clots maybe small.", patterns: ['bleed', 'pad', 'blood'], keywords: ['bleed', 'pad'] },
      { id: 'cramp', answer: "Low menstrual-on-steroids cramps.", patterns: ['cramp', 'pain'], keywords: ['cramp', 'pain'] },
      { id: 'weeks', answer: "Positive test eight weeks-ish—dating fuzzy.", patterns: ['week', 'gestation'], keywords: ['week', 'pregnant'] },
      { id: 'obhx', answer: "G2P1 healthy kid—wanted sibling story.", patterns: ['gravida', 'parity'], keywords: ['gravida', 'parity'] },
      { id: 'tissue', answer: "No obvious tissue chunk—too scared inspect.", patterns: ['tissue', 'pass'], keywords: ['tissue', 'pass'] },
      { id: 'fever', answer: "Afebrile—anxiety chills maybe.", patterns: ['fever', 'chill'], keywords: ['fever', 'chill'] },
      { id: 'uti', answer: "Bladder fine—bleeding headline.", patterns: ['uti', 'urine'], keywords: ['uti', 'urine'] },
      { id: 'movement', answer: "Squirms felt earlier—panic muffles perception.", patterns: ['movement', 'baby', 'kick'], keywords: ['movement', 'baby'] },
      { id: 'lmp', answer: "LMP buried post-positive—app guesswork.", patterns: ['lmp', 'period'], keywords: ['lmp', 'period'] },
      { id: 'sex', answer: "Nothing traumatic intercourse story.", patterns: ['sex', 'intercourse'], keywords: ['sex'] },
      { id: 'med', answer: "Prenatal vitamin—skipped ibuprofen since positive.", patterns: ['med', 'prenatal'], keywords: ['med', 'prenatal'] },
      { id: 'family', answer: "Cousin ectopic fear echo chamber.", patterns: ['family', 'cousin'], keywords: ['family', 'cousin'] },
      { id: 'discharge', answer: "Blood smell—no infection fish.", patterns: ['discharge', 'odor'], keywords: ['discharge', 'odor'] },
      { id: 'timing', answer: "Escalated today—denial yesterday.", patterns: ['when', 'timing'], keywords: ['when', 'timing'] },
      { id: 'help', answer: "Side lying slight dull—standing worse.", patterns: ['help', 'worse'], keywords: ['help', 'worse'] },
      { id: 'vague', answer: "Teacher brain offline—rephrase?", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
  {
    key: 'obgyn-pid-maria-discharge',
    titleMatchers: ['pressure', 'burning', 'down there'],
    complaintMatchers: ['pain', 'discharge'],
    defaultAnswer:
      "Pelvic pressure days—yellow-green discharge—fever 101—deep pain with sex new partner condoms missed twice. LMP two weeks ago normal. Barista on feet till dizzy.",
    qa: [
      { id: 'chief', answer: "Hurts inside—discharge gross—fever scary.", patterns: ['chief', 'bring'], keywords: ['chief'] },
      { id: 'discharge', answer: "Purulent liners—perfume cover shame.", patterns: ['discharge', 'odor'], keywords: ['discharge', 'odor'] },
      { id: 'pain', answer: "Deep ache worse sex—pressure constant.", patterns: ['pain', 'hurt', 'burn'], keywords: ['pain', 'hurt'] },
      { id: 'fever', answer: "Chills blankets 101 home thermometer.", patterns: ['fever', 'temperature'], keywords: ['fever', 'temperature'] },
      { id: 'sex', answer: "New boyfriend weeks—condoms slipped twice—judging myself hardest.", patterns: ['sex', 'partner', 'sti'], keywords: ['sex', 'partner'] },
      { id: 'lmp', answer: "Two-week-ago period baseline normal.", patterns: ['lmp', 'period'], keywords: ['lmp', 'period'] },
      { id: 'pregnancy', answer: "Don't feel pregnant—no missed scare.", patterns: ['pregnant', 'pregnancy'], keywords: ['pregnant', 'pregnancy'] },
      { id: 'uti', answer: "Urinary frequency mild—not classic razor pee.", patterns: ['uti', 'urine'], keywords: ['uti', 'urine'] },
      { id: 'nausea', answer: "Queasy feverish—not puking.", patterns: ['nausea'], keywords: ['nausea'] },
      { id: 'timing', answer: "Building shifts worsened—today peak.", patterns: ['how long', 'when'], keywords: ['long', 'when'] },
      { id: 'med', answer: "Cranberry gimmick—no antibiotics.", patterns: ['med'], keywords: ['med'] },
      { id: 'iud', answer: "No IUD history—first PID scare.", patterns: ['iud', 'prior'], keywords: ['iud', 'prior'] },
      { id: 'help', answer: "Heat pad couch minor ease.", patterns: ['help', 'worse'], keywords: ['help', 'worse'] },
      { id: 'bleed', answer: "Spotting not main—discharge stars.", patterns: ['bleed', 'spot'], keywords: ['bleed', 'spot'] },
      { id: 'family', answer: "Mom silent generation gyn—zero guidance.", patterns: ['family'], keywords: ['family'] },
      { id: 'work', answer: "Cafe shifts—stood dizzy—boss unsympathetic.", patterns: ['work', 'job'], keywords: ['work', 'job'] },
      { id: 'vague', answer: "Ask different words?", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
  {
    key: 'obgyn-preeclampsia-rebecca-headache-swelling',
    titleMatchers: ['head hurts', 'feet are swelling', 'swelling'],
    complaintMatchers: ["head won't stop", 'swelling feels worse'],
    defaultAnswer:
      "Thirty-four weeks G1P0—feet loaf-shoes—pounding headache—vision sparkles—RUQ ache after greasy food. BP scared me parking lot—not home cuff disciplined.",
    qa: [
      { id: 'chief', answer: "Headache swelling worse—triage surreal.", patterns: ['chief', 'bring'], keywords: ['chief'] },
      { id: 'head', answer: "Band squeezes—light stabs—TYLENOL weak.", patterns: ['head', 'headache', 'migraine'], keywords: ['head', 'headache'] },
      { id: 'vision', answer: "Peripheral sparkles screens—photophobia hallway.", patterns: ['vision', 'blur', 'spot'], keywords: ['vision', 'blur'] },
      { id: 'swell', answer: "Socks trench legs—hands stiff—rings gone.", patterns: ['swell', 'edema', 'feet'], keywords: ['swell', 'feet'] },
      { id: 'ruq', answer: "Right upper belly nag—greasy food trigger suspect.", patterns: ['ruq', 'epigastric'], keywords: ['ruq', 'epigastric'] },
      { id: 'weeks', answer: "Thirty-four weeks—dating US early anchored.", patterns: ['week', 'trimester', 'gestation'], keywords: ['week', 'pregnant'] },
      { id: 'obhx', answer: "G1P0 first rodeo—prenatal smooth til now.", patterns: ['gravida', 'parity'], keywords: ['gravida', 'parity'] },
      { id: 'bp', answer: "Last clinic 'fine'—ignored home monitoring—regret.", patterns: ['blood pressure', 'hypertension'], keywords: ['pressure', 'hypertension'] },
      { id: 'fever', answer: "No fever—BP headache show.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'urine', answer: "Haven't foam-noticed—trust your strips.", patterns: ['urine', 'protein'], keywords: ['urine', 'protein'] },
      { id: 'movement', answer: "Baby moves—I think—paranoid counting.", patterns: ['movement', 'baby', 'kick'], keywords: ['movement', 'baby'] },
      { id: 'sister', answer: "Sister vague high-BP pregnancy—family gossip thin.", patterns: ['family', 'sister'], keywords: ['family', 'sister'] },
      { id: 'med', answer: "Prenatal vitamin only—OTC paranoia.", patterns: ['med', 'aspirin'], keywords: ['med', 'aspirin'] },
      { id: 'timing', answer: "Swelling weeks—neuro symptoms accelerated yesterday.", patterns: ['when', 'timing'], keywords: ['when', 'timing'] },
      { id: 'help', answer: "Dark room mild relief—salt regret dinner.", patterns: ['help', 'worse'], keywords: ['help', 'worse'] },
      { id: 'seizure', answer: "Nightmare seizure threads—trying calm.", patterns: ['seizure', 'worst'], keywords: ['seizure', 'worst'] },
      { id: 'vague', answer: "Accountant precision failing—rephrase?", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
]
