import type { FallbackScenario } from './types'

export const orthopaedicSurgeryFallbackScenarios: FallbackScenario[] = [
  {
    key: 'ortho-acl-jordan-soccer-pivot',
    titleMatchers: ['heard a pop', 'pop and fell'],
    complaintMatchers: ['knee gave out'],
    defaultAnswer:
      "Planted cutting in soccer—heard a pop—not a tackle—knee swelled fast like a balloon. Crutches today; cutting sideways feels wobbly and scary for season.",
    qa: [
      { id: 'chief', answer: "Knee gave out cutting—trainer freaking—I'm trying not panic.", patterns: ['chief', 'bring'], keywords: ['chief', 'bring'] },
      { id: 'mechanism', answer: "Noncontact pivot—right foot planted—body twisted—pop audible.", patterns: ['injury', 'mechanism', 'happen'], keywords: ['injury', 'mechanism'] },
      { id: 'pop', answer: "Pop nasty rubber-band snap—teammates heard—still nauseates remembering.", patterns: ['pop', 'sound', 'snap'], keywords: ['pop', 'snap'] },
      { id: 'swell', answer: "Swelled within hour—tight pressure—trainer wrapped useless cute.", patterns: ['swell', 'effusion'], keywords: ['swell'] },
      { id: 'wb', answer: "Partial weight crutches—flat line okay—shuffle cut threatens collapse.", patterns: ['weight', 'bear', 'walk'], keywords: ['weight', 'walk'] },
      { id: 'pain', answer: "Throb deep—spikes twisting—NSAID surface help only.", patterns: ['pain', 'hurt'], keywords: ['pain', 'hurt'] },
      { id: 'sport', answer: "College soccer mid—not pro but identity bleed worry.", patterns: ['soccer', 'sport'], keywords: ['soccer', 'sport'] },
      { id: 'lock', answer: "No locked bent knee—instability fear main.", patterns: ['lock', 'catch'], keywords: ['lock', 'catch'] },
      { id: 'neuro', answer: "Foot feels normal—no dead limb—maybe guarding weak.", patterns: ['numb', 'nerve'], keywords: ['numb', 'nerve'] },
      { id: 'prior', answer: "No prior knee surgery—healthy boring until yesterday.", patterns: ['prior', 'history'], keywords: ['prior', 'history'] },
      { id: 'med', answer: "Ibuprofen trainer—no narcotics want clear head.", patterns: ['med', 'ibuprofen'], keywords: ['med'] },
      { id: 'timing', answer: "Yesterday practice timeline—hours blur adrenaline.", patterns: ['when', 'how long'], keywords: ['when', 'long'] },
      { id: 'help', answer: "Ice elevation mild—rotation cruel—sleep trash.", patterns: ['help', 'worse'], keywords: ['help', 'worse'] },
      { id: 'work', answer: "Skipped classes limping—email professor guilt.", patterns: ['school', 'work'], keywords: ['school', 'work'] },
      { id: 'fever', answer: "No fever—knee mechanical drama.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'vague', answer: "Athlete brain fog—rephrase simpler?", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
  {
    key: 'ortho-femoral-neck-margaret-kitchen-fall',
    titleMatchers: ['hip hurts', 'after i fell'],
    complaintMatchers: ["can't stand"],
    defaultAnswer:
      "Slipped kitchen tile—hip slammed—leg shortened twisted outward—cannot bear weight without shrieking—neighbor helped after embarrassing crawl.",
    qa: [
      { id: 'chief', answer: "Can't stand—hip screaming—embarrassed needing help.", patterns: ['chief', 'bring'], keywords: ['chief'] },
      { id: 'fall', answer: "Wet tile fall—no head strike thank goodness.", patterns: ['fall', 'injury'], keywords: ['fall', 'injury'] },
      { id: 'pain', answer: "Deep boring ten—rotation torture.", patterns: ['pain', 'hurt'], keywords: ['pain'] },
      { id: 'wb', answer: "Zero weight tolerance—one try countertop scream.", patterns: ['weight', 'bear', 'walk'], keywords: ['weight', 'walk'] },
      { id: 'deform', answer: "Leg shortened foot flopped outward—mirror horror.", patterns: ['rotate', 'short'], keywords: ['rotate', 'short'] },
      { id: 'head', answer: "Head never hit—hip only.", patterns: ['head', 'concussion'], keywords: ['head'] },
      { id: 'osteo', answer: "Osteoporosis years—meds adherence imperfect honesty.", patterns: ['osteoporosis', 'bone'], keywords: ['osteoporosis', 'bone'] },
      { id: 'med', answer: "Baby aspirin maybe—thick list at home.", patterns: ['med', 'blood'], keywords: ['med'] },
      { id: 'prior', answer: "Never hip replacement—virgin surgical hip.", patterns: ['prior', 'surgery'], keywords: ['prior', 'surgery'] },
      { id: 'neuro', answer: "Foot pulses weak scared—pain clouds exam.", patterns: ['numb', 'pulse'], keywords: ['numb', 'pulse'] },
      { id: 'timing', answer: "Afternoon fall—hours crawl shame—tonight ER.", patterns: ['when'], keywords: ['when'] },
      { id: 'help', answer: "Immobility slight mercy—any roll hell.", patterns: ['help', 'worse'], keywords: ['help'] },
      { id: 'alone', answer: "Live alone—neighbor rescued—daughter flying.", patterns: ['family', 'alone'], keywords: ['family', 'alone'] },
      { id: 'work', answer: "Retired librarian—books safer than floors joke.", patterns: ['work', 'job'], keywords: ['work'] },
      { id: 'fever', answer: "Chills maybe stress—not infection sure.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'vague', answer: "Pride hurt—ask clearer?", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
  {
    key: 'ortho-shoulder-dislocation-brandon-basketball',
    titleMatchers: ['shoulder came out', 'out of place'],
    complaintMatchers: ['popped out'],
    defaultAnswer:
      "Dove basketball—arm yanked backward—clunk—shoulder squared deformity—arm stuck slightly abducted—pain whiteout—maybe lateral numb patch fuzz.",
    qa: [
      { id: 'chief', answer: "Shoulder popped out—Uber shame jersey stink.", patterns: ['chief'], keywords: ['chief'] },
      { id: 'mech', answer: "ABER force diving ball—buddy landed awkward.", patterns: ['mechanism', 'basketball'], keywords: ['mechanism', 'basketball'] },
      { id: 'pop', answer: "Clunk gross audible—crowd heard.", patterns: ['pop', 'clunk'], keywords: ['pop', 'clunk'] },
      { id: 'pain', answer: "Pain ten shallow breathing—bravado cracked.", patterns: ['pain'], keywords: ['pain'] },
      { id: 'move', answer: "Cannot lower arm belt line—stuck posture.", patterns: ['move', 'lift'], keywords: ['move', 'lift'] },
      { id: 'look', answer: "Squared shoulder prominent acromion friend's words.", patterns: ['look', 'deform'], keywords: ['look', 'deform'] },
      { id: 'neuro', answer: "Lateral shoulder fuzzy numb maybe—pain interference.", patterns: ['numb', 'nerve'], keywords: ['numb'] },
      { id: 'sport', answer: "Personal trainer—dominant side—clients tomorrow panic.", patterns: ['work', 'trainer'], keywords: ['work', 'trainer'] },
      { id: 'prior', answer: "Never dislocated before—ankle trash normal.", patterns: ['prior'], keywords: ['prior'] },
      { id: 'med', answer: "Took zero meds stubborn—maybe mistake.", patterns: ['med'], keywords: ['med'] },
      { id: 'swell', answer: "Spasm swelling building—jersey hid bruise unsure.", patterns: ['swell'], keywords: ['swell'] },
      { id: 'timing', answer: "Pickup night—hours ago pain warp.", patterns: ['when'], keywords: ['when'] },
      { id: 'help', answer: "Opposite hand supports elbow only comfort.", patterns: ['help'], keywords: ['help'] },
      { id: 'fever', answer: "No fever—shoulder only.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'neck', answer: "Neck stiff compensation—shoulder villain.", patterns: ['neck'], keywords: ['neck'] },
      { id: 'vague', answer: "Clarify question pain haze?", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
  {
    key: 'ortho-scaphoid-tyler-foosh-wrist',
    titleMatchers: ['wrist hurts', 'x-ray was normal', 'xray was normal'],
    complaintMatchers: ['wrist still hurts'],
    defaultAnswer:
      "FOOSH basketball block—thumb-side snuffbox deep ache—ER X-ray negative felt rushed—grip kill—practice passes weak left—week pain persistent.",
    qa: [
      { id: 'chief', answer: "Wrist still hurts post ER 'normal' films—confused.", patterns: ['chief'], keywords: ['chief'] },
      { id: 'foosh', answer: "Fell outstretched hand blocking—wrist hyperextended ugly.", patterns: ['fall', 'foosh'], keywords: ['fall', 'foosh'] },
      { id: 'xray', answer: "Initial films labeled negative—maybe hurry—half splint worn.", patterns: ['x-ray', 'xray'], keywords: ['xray', 'film'] },
      { id: 'snuff', answer: "Snuffbox deep tender—coach pressed once—I yelped.", patterns: ['snuff', 'thumb'], keywords: ['snuff', 'thumb'] },
      { id: 'grip', answer: "Gripping bottle brutal—ball passes weak.", patterns: ['grip', 'lift'], keywords: ['grip'] },
      { id: 'swell', answer: "Mild swelling now—first night puffy worse.", patterns: ['swell'], keywords: ['swell'] },
      { id: 'neuro', answer: "Occasional palm tingle pushups—not constant numb.", patterns: ['numb'], keywords: ['numb'] },
      { id: 'sport', answer: "High school ball—ego scholarship whispers stress.", patterns: ['sport', 'school'], keywords: ['sport'] },
      { id: 'pain', answer: "Dull baseline sharp loads—five to eight scale messy.", patterns: ['pain'], keywords: ['pain'] },
      { id: 'med', answer: "Ibuprofen sporadic—stomach whine.", patterns: ['med'], keywords: ['med'] },
      { id: 'timing', answer: "Week ongoing—denial curve stupid.", patterns: ['how long'], keywords: ['long'] },
      { id: 'practice', answer: "Practice modified tape illusion stability.", patterns: ['practice'], keywords: ['practice'] },
      { id: 'help', answer: "Brace placebo mentally—grip worse overall.", patterns: ['help', 'worse'], keywords: ['help'] },
      { id: 'prior', answer: "No prior wrist fracture—ankle tween sprain ancient.", patterns: ['prior'], keywords: ['prior'] },
      { id: 'weak', answer: "Weak pushing psychologic maybe—fear dominant.", patterns: ['weak'], keywords: ['weak'] },
      { id: 'vague', answer: "Teen confused—rephrase?", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
  {
    key: 'ortho-compartment-david-construction-crush',
    titleMatchers: ["leg pain won't", 'leg pain won'],
    complaintMatchers: ['keeps getting worse'],
    defaultAnswer:
      "Rebar crushed shin hours ago—pain escalating hourly—tight shiny leg—passive toe wiggle agony—foot patch numb—construction worker embarrassed admitting severity.",
    qa: [
      { id: 'chief', answer: "Leg pain won't stop climbing—scared honest.", patterns: ['chief'], keywords: ['chief'] },
      { id: 'crush', answer: "Pinned shin trench wall rebar stack seconds eternal.", patterns: ['crush', 'injury'], keywords: ['crush', 'injury'] },
      { id: 'pain', answer: "Pain out proportion—dental Vicodin insulting useless.", patterns: ['pain'], keywords: ['pain'] },
      { id: 'tight', answer: "Shin shrink-wrap tight shiny—unnatural.", patterns: ['tight', 'swell'], keywords: ['tight'] },
      { id: 'numb', answer: "Top foot numb patch—wiggle toes pins.", patterns: ['numb'], keywords: ['numb'] },
      { id: 'stretch', answer: "Passive toe stretch lights fire—shouldn't hurt that bad.", patterns: ['stretch', 'passive'], keywords: ['stretch'] },
      { id: 'wb', answer: "Limped earlier—now fear weighting—balloon leg.", patterns: ['weight', 'walk'], keywords: ['weight', 'walk'] },
      { id: 'weak', answer: "Weak pushoff fear not paralysis textbook.", patterns: ['weak'], keywords: ['weak'] },
      { id: 'timing', answer: "Afternoon crush—evening worse—night ER.", patterns: ['hours', 'when'], keywords: ['hours', 'when'] },
      { id: 'fever', answer: "No fever—no streaking cellulitis obvious.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'med', answer: "Avoid opioids pride—maybe foolish.", patterns: ['med'], keywords: ['med'] },
      { id: 'urine', answer: "Haven't checked urine color—dehydrated day.", patterns: ['urine'], keywords: ['urine'] },
      { id: 'help', answer: "Ice elevation earlier lie comfort—spiral now.", patterns: ['help'], keywords: ['help'] },
      { id: 'boot', answer: "Steel toe maybe helped marginally—shin reality.", patterns: ['boot'], keywords: ['boot'] },
      { id: 'sport', answer: "Not athlete—job grunt—irrelevant detail.", patterns: ['sport'], keywords: ['sport'] },
      { id: 'work', answer: "Construction five years—first bad injury ego wound.", patterns: ['work'], keywords: ['work'] },
      { id: 'vague', answer: "Fog pain—simpler words?", patterns: ['understand'], keywords: ['understand'] },
    ],
  },
]
