import type { FallbackScenario } from './types'

export const urologyFallbackScenarios: FallbackScenario[] = [
  {
    key: 'urology-retention-bph-thomas-reynolds',
    titleMatchers: ["can't pee", 'cannot pee', 'bladder explode'],
    complaintMatchers: ['retention', 'suprapubic', 'unable to void'],
    defaultAnswer:
      "I haven't really urinated in half a day — lower belly feels tight like I'm going to pop. Stream's been weak forever, but today nothing comes out.",
    qa: [
      { id: 'voiding', answer: "Twelve hours of barely a dribble — pressure keeps climbing. Last decent pee was morning.", patterns: ['urine', 'void', 'pee', 'bladder'], keywords: ['urination', 'void'] },
      { id: 'pain', answer: "Low abdominal fullness that aches constant — not sharp like appendicitis stories.", patterns: ['pain', 'hurt', 'tender'], keywords: ['pain', 'hurts'] },
      { id: 'stream', answer: "Thin stop-start stream for years — hesitancy, takes forever, never feels empty.", patterns: ['stream', 'flow', 'weak'], keywords: ['stream', 'weak'] },
      { id: 'nocturia', answer: "Up several times nightly — ruins sleep before this emergency.", patterns: ['night', 'nocturia', 'sleep'], keywords: ['nighttime', 'nocturia'] },
      { id: 'fever', answer: "No fever chills — not septic feeling, just distended misery.", patterns: ['fever', 'infection'], keywords: ['fever'] },
      { id: 'blood', answer: "No obvious blood in urine today.", patterns: ['blood', 'hematuria'], keywords: ['blood'] },
      { id: 'flank', answer: "Not classic flank colic — mid-lower bladder zone pressure.", patterns: ['flank', 'kidney'], keywords: ['flank'] },
      { id: 'stone', answer: "Never passed a stone — pain pattern doesn't match buddies' stories.", patterns: ['stone'], keywords: ['stone'] },
      { id: 'sexual', answer: "Erections weaker past years — awkward detail but true.", patterns: ['sex', 'erection'], keywords: ['sexual'] },
      { id: 'meds', answer: "BP med plus sometimes cold tablets — unsure if relevant.", patterns: ['medication', 'pill'], keywords: ['medications'] },
      { id: 'family', answer: "Father had prostate issues older age.", patterns: ['family history'], keywords: ['family', 'history'] },
      { id: 'timing', answer: "Worsened hour by hour today after slowing stream weeks.", patterns: ['when', 'timing'], keywords: ['timing'] },
      { id: 'help', answer: "Nothing relieves pressure — pushing hurts more.", patterns: ['better', 'worse', 'help'], keywords: ['worse'] },
      { id: 'neuro', answer: "No numb legs or new neuro deficits.", patterns: ['spine', 'neuro'], keywords: ['neurogenic'] },
      { id: 'swell', answer: "No new scrotal swelling noticed.", patterns: ['swelling', 'scrotal'], keywords: ['swelling'] },
      { id: 'trauma', answer: "No belly trauma today.", patterns: ['trauma', 'fall'], keywords: ['trauma'] },
      { id: 'hi', answer: "Hi — I can't urinate and my bladder feels ready to burst.", patterns: ['hello', 'hi ', 'hey'], keywords: ['hello'] },
    ],
  },
  {
    key: 'urology-stone-eric-patel',
    titleMatchers: ['side hurts', 'worse than anything', 'flank'],
    complaintMatchers: ['colic', 'renal', 'stone'],
    defaultAnswer:
      "Left side pain hit like lightning — comes in waves, radiates toward my groin. Nausea and I can't get comfortable.",
    qa: [
      { id: 'flank', answer: "Left flank and back grab then release in cycles — worst pain of my life.", patterns: ['flank', 'side', 'back'], keywords: ['flank'] },
      { id: 'groin', answer: "Pain sneaks into groin and left testicle area — makes me pace the hall.", patterns: ['groin', 'testicle'], keywords: ['groin'] },
      { id: 'colic', answer: "Wave pattern — peaks where I can't breathe, lulls slightly, then slams.", patterns: ['wave', 'colic'], keywords: ['colic'] },
      { id: 'urine', answer: "Urine maybe pink — hard to tell under fluorescent lights — stings passing.", patterns: ['urine', 'void'], keywords: ['urination'] },
      { id: 'blood', answer: "Possible blood tinge — scared it's serious.", patterns: ['blood', 'red'], keywords: ['blood'] },
      { id: 'stream', answer: "Not a weak stream chronic story — acute pain owns the visit.", patterns: ['stream'], keywords: ['stream'] },
      { id: 'nausea', answer: "Dry-heaving — stomach empty but won't quit.", patterns: ['nausea', 'vomit'], keywords: ['nausea'] },
      { id: 'fever', answer: "Afebrile feeling — not rigors like infection.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'timing', answer: "Two-ish hours since sudden onset at work.", patterns: ['when', 'onset'], keywords: ['timing'] },
      { id: 'sexual', answer: "No penile discharge — not STI timing in my mind.", patterns: ['sex', 'sti'], keywords: ['sexual'] },
      { id: 'family', answer: 'Uncle had stones — family jokes about "gravel".', patterns: ['family'], keywords: ['family'] },
      { id: 'meds', answer: "Ibuprofen attempt failed.", patterns: ['medication', 'ibuprofen'], keywords: ['medications'] },
      { id: 'help', answer: "Pacing distracts seconds then worse — can't find position.", patterns: ['worse', 'better'], keywords: ['worse'] },
      { id: 'trauma', answer: "Lifted boxes but no direct nut hit — pain feels internal spasm.", patterns: ['trauma', 'lift'], keywords: ['trauma'] },
      { id: 'night', answer: "Poor sleep before but unrelated — this is new acute hell.", patterns: ['sleep', 'night'], keywords: ['sleep'] },
      { id: 'stone', answer: "No doctor confirmed stone yet — I'm scared that's what this is.", patterns: ['stone'], keywords: ['stone'] },
      { id: 'hi', answer: "Please help — my side pain is unbearable.", patterns: ['hello', 'hi '], keywords: ['hello'] },
    ],
  },
  {
    key: 'urology-hematuria-bladder-james-carter',
    titleMatchers: ['blood in urine', 'urine looked red'],
    complaintMatchers: ['hematuria', 'painless blood'],
    defaultAnswer:
      "Urine turned orange-red twice without pain — I'm a smoker and my wife is terrified. I downplayed it until she booked this.",
    qa: [
      { id: 'blood', answer: "Visible blood twice over ten days — not clot blockage.", patterns: ['blood', 'red', 'urine'], keywords: ['blood'] },
      { id: 'pain', answer: "Essentially painless — that's what scares me.", patterns: ['pain', 'burn'], keywords: ['pain'] },
      { id: 'flank', answer: "No severe flank colic.", patterns: ['flank'], keywords: ['flank'] },
      { id: 'fever', answer: "No fever.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'stream', answer: "Maybe weaker stream lately — minor compared to blood.", patterns: ['stream', 'weak'], keywords: ['stream'] },
      { id: 'nocturia', answer: "Once nightly baseline — not dramatic new frequency.", patterns: ['night'], keywords: ['nighttime'] },
      { id: 'smoke', answer: "Half pack daily decades — ashamed.", patterns: ['smoke', 'tobacco'], keywords: ['smoking'] },
      { id: 'sexual', answer: "No STI symptoms — monogamous marriage.", patterns: ['sex', 'sti'], keywords: ['sexual'] },
      { id: 'weight', answer: "No weight loss noticed.", patterns: ['weight'], keywords: ['weight'] },
      { id: 'family', answer: "No clear bladder cancer family story told.", patterns: ['family history'], keywords: ['family'] },
      { id: 'meds', answer: "Baby aspirin sometimes — ibuprofen rare.", patterns: ['medication'], keywords: ['medications'] },
      { id: 'trauma', answer: "No injury or marathon exercise trigger.", patterns: ['trauma', 'exercise'], keywords: ['trauma'] },
      { id: 'timing', answer: "Episodes mornings mostly — not exact science.", patterns: ['when'], keywords: ['timing'] },
      { id: 'help', answer: "Drinking water didn't normalize color — anxiety worse.", patterns: ['worse', 'better'], keywords: ['worse'] },
      { id: 'swell', answer: "No leg swelling.", patterns: ['swell'], keywords: ['swelling'] },
      { id: 'work', answer: "Mechanic career — chemical exposures unknown long-term.", patterns: ['work', 'job'], keywords: ['occupation'] },
      { id: 'hi', answer: "Hi — blood in my urine.", patterns: ['hello', 'hi '], keywords: ['hello'] },
    ],
  },
  {
    key: 'urology-torsion-noah-brooks',
    titleMatchers: ['testicle', 'suddenly started hurting'],
    complaintMatchers: ['torsion', 'scrotal pain'],
    defaultAnswer:
      "Left testicle exploded in pain two hours ago — nausea, can't walk normal. No sports hit I remember.",
    qa: [
      { id: 'pain', answer: "Worst pain ever — vise-like left testicle.", patterns: ['pain', 'hurt'], keywords: ['pain'] },
      { id: 'testicle', answer: "Left side wrong position maybe higher — mom noticed limp.", patterns: ['testicle', 'ball'], keywords: ['testicle'] },
      { id: 'swell', answer: "Swollen tender — can't stand fabric pressure.", patterns: ['swell'], keywords: ['swelling'] },
      { id: 'nausea', answer: "Nauseated badly — gag reflex triggered.", patterns: ['nausea'], keywords: ['nausea'] },
      { id: 'fever', answer: "No fever sense.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'urine', answer: "Urination not main story — maybe mild sting.", patterns: ['urine', 'void'], keywords: ['urination'] },
      { id: 'sex', answer: "Not sexually active — no discharge concerns.", patterns: ['sex', 'sti'], keywords: ['sexual'] },
      { id: 'trauma', answer: "No direct trauma — seated class start.", patterns: ['trauma', 'hit'], keywords: ['trauma'] },
      { id: 'timing', answer: "Two hours onset — I'm scared about delay.", patterns: ['when', 'hour'], keywords: ['timing'] },
      { id: 'prior', answer: "Never before — right side fine.", patterns: ['prior', 'before'], keywords: ['prior'] },
      { id: 'family', answer: "No family torsion talk.", patterns: ['family'], keywords: ['family'] },
      { id: 'meds', answer: "No prescriptions — parent ibuprofen useless.", patterns: ['medication'], keywords: ['medications'] },
      { id: 'stream', answer: "Not chronic stream issue — acute event.", patterns: ['stream'], keywords: ['stream'] },
      { id: 'flank', answer: "Not flank — groin testicle localized.", patterns: ['flank'], keywords: ['flank'] },
      { id: 'help', answer: "Hand support helps split-second — jostle kills.", patterns: ['help', 'worse'], keywords: ['worse'] },
      { id: 'blood', answer: "No hematuria seen.", patterns: ['blood'], keywords: ['blood'] },
      { id: 'urgency', answer: "I overheard time matters for salvage — I'm panicked.", patterns: ['time', 'hour', 'salvage'], keywords: ['timing'] },
      { id: 'hi', answer: "Hi — sudden severe testicle pain.", patterns: ['hello', 'hi '], keywords: ['hello'] },
    ],
  },
  {
    key: 'urology-bph-luts-robert-kim',
    titleMatchers: ['bathroom at night', 'running to the bathroom'],
    complaintMatchers: ['nocturia', 'LUTS', 'BPH'],
    defaultAnswer:
      "Up all night peeing — weak stream and dribble years. Exhausted retired teacher missing sleep.",
    qa: [
      { id: 'night', answer: "Four to five nightly voids — destroys sleep quality.", patterns: ['night', 'nocturia'], keywords: ['nighttime'] },
      { id: 'stream', answer: "Weak intermittent stream — double void sometimes.", patterns: ['stream', 'weak'], keywords: ['stream'] },
      { id: 'dribble', answer: "Post-void dribble stains — embarrassing.", patterns: ['dribbl', 'empty'], keywords: ['dribbling'] },
      { id: 'frequency', answer: "Daytime frequency urgency after coffee — golf buddies notice.", patterns: ['frequency', 'urgency'], keywords: ['urination'] },
      { id: 'pain', answer: "Minimal dysuria — not infection picture.", patterns: ['pain', 'burn'], keywords: ['pain'] },
      { id: 'blood', answer: "No visible blood.", patterns: ['blood'], keywords: ['blood'] },
      { id: 'flank', answer: "No flank pain.", patterns: ['flank'], keywords: ['flank'] },
      { id: 'fever', answer: "Afebrile chronic course.", patterns: ['fever'], keywords: ['fever'] },
      { id: 'sexual', answer: "Erections weaker — ejaculation less force — shy topic.", patterns: ['erect', 'sex'], keywords: ['sexual'] },
      { id: 'diabetes', answer: "No diabetes label — thirst not crazy.", patterns: ['diabetes', 'sugar'], keywords: ['diabetes'] },
      { id: 'family', answer: "Father prostate procedures murmured.", patterns: ['family'], keywords: ['family'] },
      { id: 'meds', answer: "Lisinopril — seasonal antihistamine summers.", patterns: ['medication', 'lisinopril'], keywords: ['medications'] },
      { id: 'timing', answer: "Years gradual — not single acute blockage yet.", patterns: ['when', 'long'], keywords: ['timing'] },
      { id: 'help', answer: "Less evening coffee helps slightly — alcohol worsens nights.", patterns: ['better', 'worse'], keywords: ['better'] },
      { id: 'swell', answer: "No scrotal edema.", patterns: ['swell'], keywords: ['swelling'] },
      { id: 'retention', answer: "Not complete anuria — feared that scenario.", patterns: ['retention', 'can\'t pee'], keywords: ['retention'] },
      { id: 'weight', answer: "Weight stable.", patterns: ['weight'], keywords: ['weight'] },
      { id: 'hi', answer: "Hi — nocturia killing my sleep.", patterns: ['hello', 'hi '], keywords: ['hello'] },
    ],
  },
]
